// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using suplex_projektmunka.Models.Context;

#nullable disable

namespace suplex_projektmunka.Migrations
{
    [DbContext(typeof(GymContext))]
    [Migration("20260420154748_AddStaffRoleAndSeededItems")]
    partial class AddStaffRoleAndSeededItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("suplex_projektmunka.Models.FrontendExtraData.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.FrontendExtraData.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("User_id")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cart_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Item_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Cart_id");

                    b.HasIndex("Item_id")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValidityDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Type_id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Full facility access for one day. No commitment required.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Daily Pass",
                            Price = 2900,
                            Type_id = 1,
                            ValidityDays = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Unlimited access for 30 days. Includes all group classes.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Monthly Pass",
                            Price = 12900,
                            Type_id = 2,
                            ValidityDays = 30
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "90 days of unlimited access. Great value for committed trainers.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Seasonal Pass",
                            Price = 32900,
                            Type_id = 4,
                            ValidityDays = 90
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Best value — full access for 365 days. Priority booking included.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Annual Pass",
                            Price = 99900,
                            Type_id = 3,
                            ValidityDays = 365
                        });
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.PurchaseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.ToTable("PurchaseDetails");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.PurchaseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Item_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<int>("Purchase_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QrCodeData")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Item_id");

                    b.HasIndex("Purchase_id");

                    b.ToTable("PurchaseItems");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.Types", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "daily"
                        },
                        new
                        {
                            Id = 2,
                            Type = "monthly"
                        },
                        new
                        {
                            Id = 3,
                            Type = "annual"
                        },
                        new
                        {
                            Id = 4,
                            Type = "seasonal"
                        });
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.BillingAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ZIP_code")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BillingAddress");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "user"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "staff"
                        });
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Animation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BillingAddress_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JWT_token")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PurchaseDetailId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Settings_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillingAddress_id");

                    b.HasIndex("PurchaseDetailId");

                    b.HasIndex("Role_id");

                    b.HasIndex("SettingsId");

                    b.HasIndex("Settings_id")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.Cart", b =>
                {
                    b.HasOne("suplex_projektmunka.Models.UserData.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("suplex_projektmunka.Models.ItemPurchases.Cart", "User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.CartItem", b =>
                {
                    b.HasOne("suplex_projektmunka.Models.ItemPurchases.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("Cart_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("suplex_projektmunka.Models.ItemPurchases.Item", "Item")
                        .WithOne("CartItem")
                        .HasForeignKey("suplex_projektmunka.Models.ItemPurchases.CartItem", "Item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.Item", b =>
                {
                    b.HasOne("suplex_projektmunka.Models.ItemPurchases.Types", "Type")
                        .WithMany("Items")
                        .HasForeignKey("Type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.PurchaseDetail", b =>
                {
                    b.HasOne("suplex_projektmunka.Models.UserData.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.PurchaseItem", b =>
                {
                    b.HasOne("suplex_projektmunka.Models.ItemPurchases.Item", "Item")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("Item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("suplex_projektmunka.Models.ItemPurchases.PurchaseDetail", "PurchaseDetail")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("Purchase_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("PurchaseDetail");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.User", b =>
                {
                    b.HasOne("suplex_projektmunka.Models.UserData.BillingAddress", "BillingAddress")
                        .WithMany("Users")
                        .HasForeignKey("BillingAddress_id");

                    b.HasOne("suplex_projektmunka.Models.ItemPurchases.PurchaseDetail", "PurchaseDetail")
                        .WithMany()
                        .HasForeignKey("PurchaseDetailId");

                    b.HasOne("suplex_projektmunka.Models.UserData.Roles", "Roles")
                        .WithMany("Users")
                        .HasForeignKey("Role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("suplex_projektmunka.Models.UserData.Settings", null)
                        .WithMany("Users")
                        .HasForeignKey("SettingsId");

                    b.HasOne("suplex_projektmunka.Models.UserData.Settings", "Settings")
                        .WithOne()
                        .HasForeignKey("suplex_projektmunka.Models.UserData.User", "Settings_id");

                    b.Navigation("BillingAddress");

                    b.Navigation("PurchaseDetail");

                    b.Navigation("Roles");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.Item", b =>
                {
                    b.Navigation("CartItem");

                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.PurchaseDetail", b =>
                {
                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.Types", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.BillingAddress", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.Settings", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.User", b =>
                {
                    b.Navigation("Cart");
                });
#pragma warning restore 612, 618
        }
    }
}
