// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using suplex_projektmunka.Models.Context;

#nullable disable

namespace suplex_projektmunka.Migrations
{
    [DbContext(typeof(GymContext))]
    [Migration("20260421145527_SeedDemoData")]
    partial class SeedDemoData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("suplex_projektmunka.Models.FrontendExtraData.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Futópad #1",
                            SerialNumber = 129942,
                            Status = "out_of_order"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Futópad #2",
                            SerialNumber = 129943,
                            Status = "operational"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Futópad #3",
                            SerialNumber = 129944,
                            Status = "operational"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Futópad #4",
                            SerialNumber = 129945,
                            Status = "maintenance"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Szobabicikli #1",
                            SerialNumber = 230001,
                            Status = "operational"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Szobabicikli #2",
                            SerialNumber = 230002,
                            Status = "operational"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spinningkerékpár #1",
                            SerialNumber = 230010,
                            Status = "operational"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spinningkerékpár #2",
                            SerialNumber = 230011,
                            Status = "operational"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Elliptikus tréner #1",
                            SerialNumber = 340001,
                            Status = "operational"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Elliptikus tréner #2",
                            SerialNumber = 340002,
                            Status = "maintenance"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Evezőgép",
                            SerialNumber = 340010,
                            Status = "operational"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mellprésgép",
                            SerialNumber = 450001,
                            Status = "operational"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lábprésgép",
                            SerialNumber = 450002,
                            Status = "operational"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lat pulldown gép",
                            SerialNumber = 450003,
                            Status = "operational"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kábelgép (cross)",
                            SerialNumber = 450004,
                            Status = "out_of_order"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Smith gép",
                            SerialNumber = 450010,
                            Status = "operational"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Scottpad",
                            SerialNumber = 450011,
                            Status = "operational"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Szabadsúly állvány #1",
                            SerialNumber = 560001,
                            Status = "operational"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Szabadsúly állvány #2",
                            SerialNumber = 560002,
                            Status = "operational"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Guggolóállvány",
                            SerialNumber = 560010,
                            Status = "maintenance"
                        });
                });

            modelBuilder.Entity("suplex_projektmunka.Models.FrontendExtraData.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Örömmel jelentjük be, hogy a Suplex Gym hivatalosan is megnyitotta kapuit! Korszerű gépparkunk, tágas öltözőink és tapasztalt edzőink várják az edzeni vágyókat hétfőtől szombatig 6:00-tól 22:00-ig. Látogass el hozzánk és próbáld ki az első edzést ingyen!",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "",
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Megnyitottunk!"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Februártól bővítjük csoportos óráink kínálatát! Hetente háromszor tartunk spinning, jóga és HIIT edzést is. A bérletes tagoknak az összes csoportos óra ingyenes. Időpontok és helyek korlátozottak, előre foglalás ajánlott az edzőknél.",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "",
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Új csoportos edzések"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Március 15-től április 30-ig minden új bérlet vásárlásakor 20% kedvezményt adunk! Ez vonatkozik a havi, szezonális és éves bérletekre egyaránt. Ne hagyd ki – ez az ajánlatunk korlátozott ideig él. Vásárold meg most az alkalmazáson keresztül!",
                            CreatedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "",
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tavaszi akció – 20% kedvezmény"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Tudjuk, mennyire fontos a mozgás minden életszakaszban. Diákok és nyugdíjasok érvényes igazolvánnyal 30%-os kedvezménnyel vásárolhatnak bérletet a recepción. A mozgás mindenkinek jár – segítünk abban, hogy elérhető legyen számodra is.",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "",
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Diák- és nyugdíjasakció"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Tájékoztatjuk tagjainkat, hogy április 28-án (hétfőn) reggel 6:00 és 10:00 között technikai karbantartás miatt zárva tartunk. A szünet alatt új futópadokat és szabad súlyos eszközöket helyezünk üzembe. Elnézést kérünk az esetleges kellemetlenségekért!",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "",
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Karbantartási szünet"
                        });
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("User_id")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cart_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Item_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Cart_id");

                    b.HasIndex("Item_id")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValidityDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Type_id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teljes hozzáférés egy napra. Nincs kötelezettség.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Napijegy",
                            Price = 2900,
                            Type_id = 1,
                            ValidityDays = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Korlátlan hozzáférés 30 napra. Részt vehetsz az összes csoportos edzésen.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Havi bérlet",
                            Price = 12900,
                            Type_id = 2,
                            ValidityDays = 30
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "90 nap korlátlan hozzáférés. Kiváló választás elkötelezett edzeni vágyóknak.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Szezonális bérlet",
                            Price = 32900,
                            Type_id = 4,
                            ValidityDays = 90
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Legjobb ár-érték arány – teljes hozzáférés 365 napra.",
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Éves bérlet",
                            Price = 99900,
                            Type_id = 3,
                            ValidityDays = 365
                        });
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.PurchaseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.ToTable("PurchaseDetails");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.PurchaseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Item_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<int>("Purchase_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QrCodeData")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Item_id");

                    b.HasIndex("Purchase_id");

                    b.ToTable("PurchaseItems");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.Types", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "napi"
                        },
                        new
                        {
                            Id = 2,
                            Type = "havi"
                        },
                        new
                        {
                            Id = 3,
                            Type = "éves"
                        },
                        new
                        {
                            Id = 4,
                            Type = "szezonális"
                        });
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.BillingAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ZIP_code")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BillingAddress");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "user"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "staff"
                        });
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Animation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Animation = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DarkMode = false,
                            IsActive = true,
                            Language = "hu",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Animation = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DarkMode = true,
                            IsActive = true,
                            Language = "hu",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Animation = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DarkMode = false,
                            IsActive = true,
                            Language = "hu",
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BillingAddress_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JWT_token")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PurchaseDetailId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Settings_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillingAddress_id");

                    b.HasIndex("PurchaseDetailId");

                    b.HasIndex("Role_id");

                    b.HasIndex("SettingsId");

                    b.HasIndex("Settings_id")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@suplexgym.hu",
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Suplex Admin",
                            PasswordHash = "$2a$11$k7a2vkvbZMmodCBgocWMAeS7Ys6rubYQLMpogAZkdi50JftM6zCPq",
                            Role_id = 1,
                            Settings_id = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "peter@suplexgym.hu",
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kovács Péter",
                            PasswordHash = "$2b$11$pkOPLWmS/dgVTR6CKSiePupIjHvBoRMaklmm0mCItpDSSlqJ6FYEW",
                            Role_id = 3,
                            Settings_id = 2,
                            Username = "kpeter"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna@gmail.com",
                            IsActive = true,
                            ModifiedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nagy Anna",
                            PasswordHash = "$2b$11$sfOyEWXVYffY0c.4sGXyZudGuKQl//zIGmVU.2sYz2sD.zuwXoCSm",
                            Role_id = 2,
                            Settings_id = 3,
                            Username = "nanna"
                        });
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.Cart", b =>
                {
                    b.HasOne("suplex_projektmunka.Models.UserData.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("suplex_projektmunka.Models.ItemPurchases.Cart", "User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.CartItem", b =>
                {
                    b.HasOne("suplex_projektmunka.Models.ItemPurchases.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("Cart_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("suplex_projektmunka.Models.ItemPurchases.Item", "Item")
                        .WithOne("CartItem")
                        .HasForeignKey("suplex_projektmunka.Models.ItemPurchases.CartItem", "Item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.Item", b =>
                {
                    b.HasOne("suplex_projektmunka.Models.ItemPurchases.Types", "Type")
                        .WithMany("Items")
                        .HasForeignKey("Type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.PurchaseDetail", b =>
                {
                    b.HasOne("suplex_projektmunka.Models.UserData.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.PurchaseItem", b =>
                {
                    b.HasOne("suplex_projektmunka.Models.ItemPurchases.Item", "Item")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("Item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("suplex_projektmunka.Models.ItemPurchases.PurchaseDetail", "PurchaseDetail")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("Purchase_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("PurchaseDetail");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.User", b =>
                {
                    b.HasOne("suplex_projektmunka.Models.UserData.BillingAddress", "BillingAddress")
                        .WithMany("Users")
                        .HasForeignKey("BillingAddress_id");

                    b.HasOne("suplex_projektmunka.Models.ItemPurchases.PurchaseDetail", "PurchaseDetail")
                        .WithMany()
                        .HasForeignKey("PurchaseDetailId");

                    b.HasOne("suplex_projektmunka.Models.UserData.Roles", "Roles")
                        .WithMany("Users")
                        .HasForeignKey("Role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("suplex_projektmunka.Models.UserData.Settings", null)
                        .WithMany("Users")
                        .HasForeignKey("SettingsId");

                    b.HasOne("suplex_projektmunka.Models.UserData.Settings", "Settings")
                        .WithOne()
                        .HasForeignKey("suplex_projektmunka.Models.UserData.User", "Settings_id");

                    b.Navigation("BillingAddress");

                    b.Navigation("PurchaseDetail");

                    b.Navigation("Roles");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.Item", b =>
                {
                    b.Navigation("CartItem");

                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.PurchaseDetail", b =>
                {
                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.ItemPurchases.Types", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.BillingAddress", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.Settings", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("suplex_projektmunka.Models.UserData.User", b =>
                {
                    b.Navigation("Cart");
                });
#pragma warning restore 612, 618
        }
    }
}